/*
 * constants.h
 *
 *  Created on: Nov 15, 2022
 *      Author: matt
 */

#ifndef PHYSICSENGINE_CONSTANTS_H_
#define PHYSICSENGINE_CONSTANTS_H_

#define SCREEN_PIXELS 128u
#define SCREEN_MM 23.04
#define PHYSICS_PERIOD 1
//#define PHYSICS_DELTA PHYSICS_PERIOD/1000
//#define GRAVITY_PIXELS GRAVITY * SCREEN_PIXELS / SCREEN_MM
//#define PASSIVE_KENETIC_REDUCTION 0.9
#define CANYON_SIZE_PIXELS 118
#define CANYON_SIZE_MM (CANYON_SIZE_PIXELS * SCREEN_MM/SCREEN_PIXELS)
#define NORMAL_PRIO 21
#define LOWER_PRIO (NORMAL_PRIO + 1)
#define HIGHER_PRIO (NORMAL_PRIO - 1)
#define CANYON_START ((SCREEN_PIXELS - CANYON_SIZE_PIXELS) / 2)
#define CANYON_END (SCREEN_PIXELS - CANYON_START)


#endif /* PHYSICSENGINE_CONSTANTS_H_ */
